package main.java.generator;

import main.java.declare.core.Template;

public class ASPProgramUtility {
	public static final String LP_GENERATION_PROBLEM = 
			"time(1..t). %t = lunghezza traccia\n"
			+ "\n"
			+ "cur_state(I,S,0) :- initial(Name,S),template(I,Name).\n"
			+ "\n"
			+ "{trace(A,T) : activity(A)} = 1 :- time(T).\n"
			+ "{assigned_value(K,V,T) : value(K,V)} = 1 :- trace(A,T), has_attribute(A,K).\n"
			+ "\n"
			+ "\n"
			+ "cur_state(I,S2,T) :- cur_state(I,S1,T-1), template(I,Name), automaton(Name,S1,c,S2), trace(A,T), not activation(I,A), not target(I,A).\n"
			+ "cur_state(I,S2,T) :- cur_state(I,S1,T-1), template(I,Name), automaton(Name,S1,c,S2), trace(A,T), activation(I,A), not activation_condition(I,T).\n"
			+ "cur_state(I,S2,T) :- cur_state(I,S1,T-1), template(I,Name), automaton(Name,S1,a,S2), trace(A,T), activation(I,A), activation_condition(I,T).\n"
			+ "cur_state(I,S2,T) :- cur_state(I,S1,T-1), template(I,Name), automaton(Name,S1,c,S2), trace(A,T), target(I,A), not correlation_condition(I,T).\n"
			+ "cur_state(I,S2,T) :- cur_state(I,S1,T-1), template(I,Name), automaton(Name,S1,b,S2), trace(A,T), target(I,A), correlation_condition(I,T).\n"
			+ "\n"
			+ "\n"
			+ "sat(I,T) :- cur_state(I,S,T), template(I,Name), accepting(Name,S). \n"
			+ "\n"
			+ ":- template(I,_), not  sat(I,t).\n"
			+ "\n"
			+ "#show trace/2.\n"
			+ "#show assigned_value/3.\n"
			+ "%#show sat/2.\n";
	
	public static final String LP_TEMPLATES = 
			"automaton(\"" + Template.ABSENCE2 + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.ABSENCE2 + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.ABSENCE2 + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.ABSENCE2 + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.ABSENCE2 + "\",s_1,a,s_2).\n"
			+ "automaton(\"" + Template.ABSENCE2 + "\",s_0,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.ABSENCE2 + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.ABSENCE2 + "\",s_0).\n"
			+ "accepting(\"" + Template.ABSENCE2 + "\",s_1).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.ABSENCE3 + "\",s_0,a,s_3).\n"
			+ "automaton(\"" + Template.ABSENCE3 + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.ABSENCE3 + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.ABSENCE3 + "\",s_3,c,s_3).\n"
			+ "automaton(\"" + Template.ABSENCE3 + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.ABSENCE3 + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.ABSENCE3 + "\",s_3,a,s_1).\n"
			+ "automaton(\"" + Template.ABSENCE3 + "\",s_1,a,s_2).\n"
			+ "\n"
			+ "initial(\"" + Template.ABSENCE3 + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.ABSENCE3 + "\",s_0).\n"
			+ "accepting(\"" + Template.ABSENCE3 + "\",s_1).\n"
			+ "accepting(\"" + Template.ABSENCE3 + "\",s_3).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.ABSENCE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.ABSENCE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.ABSENCE + "\",s_1,a,s_1).\n"
			+ "automaton(\"" + Template.ABSENCE + "\",s_0,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.ABSENCE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.ABSENCE + "\",s_0).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_3,c,s_3).\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_0,c,s_4).\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_1,a,s_3).\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_1,c,s_3).\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_0,a,s_2).\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_2,b,s_4).\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_0,b,s_3).\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_4,a,s_2).\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_4,c,s_4).\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_3,a,s_3).\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_3,b,s_3).\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_4,b,s_3).\n"
			+ "automaton(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_1,b,s_3).\n"
			+ "\n"
			+ "initial(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_0).\n"
			+ "accepting(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_1).\n"
			+ "accepting(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_2).\n"
			+ "accepting(\"" + Template.ALTERNATE_PRECEDENCE + "\",s_4).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.ALTERNATE_RESPONSE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.ALTERNATE_RESPONSE + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.ALTERNATE_RESPONSE + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.ALTERNATE_RESPONSE + "\",s_2,b,s_2).\n"
			+ "automaton(\"" + Template.ALTERNATE_RESPONSE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.ALTERNATE_RESPONSE + "\",s_0,b,s_0).\n"
			+ "automaton(\"" + Template.ALTERNATE_RESPONSE + "\",s_0,a,s_1).\n"
			+ "automaton(\"" + Template.ALTERNATE_RESPONSE + "\",s_1,a,s_2).\n"
			+ "automaton(\"" + Template.ALTERNATE_RESPONSE + "\",s_1,b,s_0).\n"
			+ "\n"
			+ "initial(\"" + Template.ALTERNATE_RESPONSE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.ALTERNATE_RESPONSE + "\",s_0).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.ALTERNATE_SUCCESSION + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.ALTERNATE_SUCCESSION + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.ALTERNATE_SUCCESSION + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.ALTERNATE_SUCCESSION + "\",s_2,b,s_2).\n"
			+ "automaton(\"" + Template.ALTERNATE_SUCCESSION + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.ALTERNATE_SUCCESSION + "\",s_1,a,s_2).\n"
			+ "automaton(\"" + Template.ALTERNATE_SUCCESSION + "\",s_0,a,s_1).\n"
			+ "automaton(\"" + Template.ALTERNATE_SUCCESSION + "\",s_1,b,s_0).\n"
			+ "automaton(\"" + Template.ALTERNATE_SUCCESSION + "\",s_0,b,s_2).\n"
			+ "\n"
			+ "initial(\"" + Template.ALTERNATE_SUCCESSION + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.ALTERNATE_SUCCESSION + "\",s_0).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_4,c,s_2).\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_4,b,s_2).\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_2,b,s_3).\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_0,b,s_1).\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_3,c,s_3).\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_1,c,s_3).\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_1,a,s_3).\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_2,a,s_4).\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_3,a,s_3).\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_3,b,s_3).\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_0,a,s_4).\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_4,a,s_4).\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_0,c,s_2).\n"
			+ "automaton(\"" + Template.CHAIN_PRECEDENCE + "\",s_1,b,s_3).\n"
			+ "\n"
			+ "initial(\"" + Template.CHAIN_PRECEDENCE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.CHAIN_PRECEDENCE + "\",s_0).\n"
			+ "accepting(\"" + Template.CHAIN_PRECEDENCE + "\",s_1).\n"
			+ "accepting(\"" + Template.CHAIN_PRECEDENCE + "\",s_2).\n"
			+ "accepting(\"" + Template.CHAIN_PRECEDENCE + "\",s_4).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.CHAIN_RESPONSE + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.CHAIN_RESPONSE + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.CHAIN_RESPONSE + "\",s_2,b,s_2).\n"
			+ "automaton(\"" + Template.CHAIN_RESPONSE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.CHAIN_RESPONSE + "\",s_0,b,s_0).\n"
			+ "automaton(\"" + Template.CHAIN_RESPONSE + "\",s_0,a,s_1).\n"
			+ "automaton(\"" + Template.CHAIN_RESPONSE + "\",s_1,a,s_2).\n"
			+ "automaton(\"" + Template.CHAIN_RESPONSE + "\",s_1,c,s_2).\n"
			+ "automaton(\"" + Template.CHAIN_RESPONSE + "\",s_1,b,s_0).\n"
			+ "\n"
			+ "initial(\"" + Template.CHAIN_RESPONSE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.CHAIN_RESPONSE + "\",s_0).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_0,a,s_3).\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_0,c,s_4).\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_2,c,s_1).\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_3,b,s_4).\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_4,a,s_3).\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_4,b,s_1).\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_1,b,s_1).\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_3,a,s_1).\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_4,c,s_4).\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_2,a,s_1).\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_2,b,s_1).\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_1,a,s_1).\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_3,c,s_1).\n"
			+ "automaton(\"" + Template.CHAIN_SUCCESSION + "\",s_0,b,s_2).\n"
			+ "\n"
			+ "initial(\"" + Template.CHAIN_SUCCESSION + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.CHAIN_SUCCESSION + "\",s_0).\n"
			+ "accepting(\"" + Template.CHAIN_SUCCESSION + "\",s_2).\n"
			+ "accepting(\"" + Template.CHAIN_SUCCESSION + "\",s_4).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.CHOICE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.CHOICE + "\",s_0,b,s_1).\n"
			+ "automaton(\"" + Template.CHOICE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.CHOICE + "\",s_1,b,s_1).\n"
			+ "automaton(\"" + Template.CHOICE + "\",s_0,a,s_1).\n"
			+ "automaton(\"" + Template.CHOICE + "\",s_1,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.CHOICE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.CHOICE + "\",s_1).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.CO_EXISTENCE + "\",s_0,a,s_3).\n"
			+ "automaton(\"" + Template.CO_EXISTENCE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.CO_EXISTENCE + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.CO_EXISTENCE + "\",s_3,b,s_1).\n"
			+ "automaton(\"" + Template.CO_EXISTENCE + "\",s_3,c,s_3).\n"
			+ "automaton(\"" + Template.CO_EXISTENCE + "\",s_2,b,s_2).\n"
			+ "automaton(\"" + Template.CO_EXISTENCE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.CO_EXISTENCE + "\",s_1,b,s_1).\n"
			+ "automaton(\"" + Template.CO_EXISTENCE + "\",s_2,a,s_1).\n"
			+ "automaton(\"" + Template.CO_EXISTENCE + "\",s_1,a,s_1).\n"
			+ "automaton(\"" + Template.CO_EXISTENCE + "\",s_3,a,s_3).\n"
			+ "automaton(\"" + Template.CO_EXISTENCE + "\",s_0,b,s_2).\n"
			+ "\n"
			+ "initial(\"" + Template.CO_EXISTENCE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.CO_EXISTENCE + "\",s_0).\n"
			+ "accepting(\"" + Template.CO_EXISTENCE + "\",s_1).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.END + "\",s_1,c,s_0).\n"
			+ "automaton(\"" + Template.END + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.END + "\",s_1,a,s_1).\n"
			+ "automaton(\"" + Template.END + "\",s_0,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.END + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.END + "\",s_1).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.EXACTLY1 + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.EXACTLY1 + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.EXACTLY1 + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.EXACTLY1 + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.EXACTLY1 + "\",s_1,a,s_2).\n"
			+ "automaton(\"" + Template.EXACTLY1 + "\",s_0,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.EXACTLY1 + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.EXACTLY1 + "\",s_1).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.EXACTLY2 + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.EXACTLY2 + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.EXACTLY2 + "\",s_3,c,s_3).\n"
			+ "automaton(\"" + Template.EXACTLY2 + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.EXACTLY2 + "\",s_3,a,s_2).\n"
			+ "automaton(\"" + Template.EXACTLY2 + "\",s_1,a,s_3).\n"
			+ "automaton(\"" + Template.EXACTLY2 + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.EXACTLY2 + "\",s_0,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.EXACTLY2 + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.EXACTLY2 + "\",s_3).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.EXCLUSIVE_CHOICE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.EXCLUSIVE_CHOICE + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.EXCLUSIVE_CHOICE + "\",s_2,b,s_3).\n"
			+ "automaton(\"" + Template.EXCLUSIVE_CHOICE + "\",s_0,b,s_1).\n"
			+ "automaton(\"" + Template.EXCLUSIVE_CHOICE + "\",s_3,c,s_3).\n"
			+ "automaton(\"" + Template.EXCLUSIVE_CHOICE + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.EXCLUSIVE_CHOICE + "\",s_1,a,s_3).\n"
			+ "automaton(\"" + Template.EXCLUSIVE_CHOICE + "\",s_0,a,s_2).\n"
			+ "automaton(\"" + Template.EXCLUSIVE_CHOICE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.EXCLUSIVE_CHOICE + "\",s_1,b,s_1).\n"
			+ "automaton(\"" + Template.EXCLUSIVE_CHOICE + "\",s_3,b,s_3).\n"
			+ "automaton(\"" + Template.EXCLUSIVE_CHOICE + "\",s_3,a,s_3).\n"
			+ "\n"
			+ "initial(\"" + Template.EXCLUSIVE_CHOICE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.EXCLUSIVE_CHOICE + "\",s_1).\n"
			+ "accepting(\"" + Template.EXCLUSIVE_CHOICE + "\",s_2).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.EXISTENCE2 + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.EXISTENCE2 + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.EXISTENCE2 + "\",s_0,a,s_2).\n"
			+ "automaton(\"" + Template.EXISTENCE2 + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.EXISTENCE2 + "\",s_2,a,s_1).\n"
			+ "automaton(\"" + Template.EXISTENCE2 + "\",s_1,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.EXISTENCE2 + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.EXISTENCE2 + "\",s_1).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.EXISTENCE3 + "\",s_0,a,s_3).\n"
			+ "automaton(\"" + Template.EXISTENCE3 + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.EXISTENCE3 + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.EXISTENCE3 + "\",s_3,c,s_3).\n"
			+ "automaton(\"" + Template.EXISTENCE3 + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.EXISTENCE3 + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.EXISTENCE3 + "\",s_3,a,s_1).\n"
			+ "automaton(\"" + Template.EXISTENCE3 + "\",s_1,a,s_2).\n"
			+ "\n"
			+ "initial(\"" + Template.EXISTENCE3 + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.EXISTENCE3 + "\",s_2).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.EXISTENCE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.EXISTENCE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.EXISTENCE + "\",s_1,a,s_1).\n"
			+ "automaton(\"" + Template.EXISTENCE + "\",s_0,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.EXISTENCE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.EXISTENCE + "\",s_1).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.INIT + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.INIT + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.INIT + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.INIT + "\",s_0,a,s_1).\n"
			+ "automaton(\"" + Template.INIT + "\",s_1,a,s_1).\n"
			+ "automaton(\"" + Template.INIT + "\",s_0,c,s_2).\n"
			+ "\n"
			+ "initial(\"" + Template.INIT + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.INIT + "\",s_1).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.NOT_CHAIN_PRECEDENCE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_PRECEDENCE + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_PRECEDENCE + "\",s_0,a,s_2).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_PRECEDENCE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_PRECEDENCE + "\",s_1,b,s_1).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_PRECEDENCE + "\",s_0,b,s_0).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_PRECEDENCE + "\",s_2,c,s_0).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_PRECEDENCE + "\",s_2,b,s_1).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_PRECEDENCE + "\",s_1,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.NOT_CHAIN_PRECEDENCE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.NOT_CHAIN_PRECEDENCE + "\",s_0).\n"
			+ "accepting(\"" + Template.NOT_CHAIN_PRECEDENCE + "\",s_2).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.NOT_CHAIN_RESPONSE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_RESPONSE + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_RESPONSE + "\",s_0,a,s_2).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_RESPONSE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_RESPONSE + "\",s_1,b,s_1).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_RESPONSE + "\",s_0,b,s_0).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_RESPONSE + "\",s_2,c,s_0).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_RESPONSE + "\",s_2,b,s_1).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_RESPONSE + "\",s_1,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.NOT_CHAIN_RESPONSE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.NOT_CHAIN_RESPONSE + "\",s_0).\n"
			+ "accepting(\"" + Template.NOT_CHAIN_RESPONSE + "\",s_2).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.NOT_CHAIN_SUCCESSION + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_SUCCESSION + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_SUCCESSION + "\",s_0,a,s_2).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_SUCCESSION + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_SUCCESSION + "\",s_1,b,s_1).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_SUCCESSION + "\",s_0,b,s_0).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_SUCCESSION + "\",s_2,c,s_0).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_SUCCESSION + "\",s_2,b,s_1).\n"
			+ "automaton(\"" + Template.NOT_CHAIN_SUCCESSION + "\",s_1,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.NOT_CHAIN_SUCCESSION + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.NOT_CHAIN_SUCCESSION + "\",s_0).\n"
			+ "accepting(\"" + Template.NOT_CHAIN_SUCCESSION + "\",s_2).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.NOT_CO_EXISTENCE + "\",s_0,a,s_3).\n"
			+ "automaton(\"" + Template.NOT_CO_EXISTENCE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.NOT_CO_EXISTENCE + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.NOT_CO_EXISTENCE + "\",s_3,b,s_1).\n"
			+ "automaton(\"" + Template.NOT_CO_EXISTENCE + "\",s_3,c,s_3).\n"
			+ "automaton(\"" + Template.NOT_CO_EXISTENCE + "\",s_2,b,s_2).\n"
			+ "automaton(\"" + Template.NOT_CO_EXISTENCE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.NOT_CO_EXISTENCE + "\",s_1,b,s_1).\n"
			+ "automaton(\"" + Template.NOT_CO_EXISTENCE + "\",s_2,a,s_1).\n"
			+ "automaton(\"" + Template.NOT_CO_EXISTENCE + "\",s_1,a,s_1).\n"
			+ "automaton(\"" + Template.NOT_CO_EXISTENCE + "\",s_3,a,s_3).\n"
			+ "automaton(\"" + Template.NOT_CO_EXISTENCE + "\",s_0,b,s_2).\n"
			+ "\n"
			+ "initial(\"" + Template.NOT_CO_EXISTENCE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.NOT_CO_EXISTENCE + "\",s_0).\n"
			+ "accepting(\"" + Template.NOT_CO_EXISTENCE + "\",s_2).\n"
			+ "accepting(\"" + Template.NOT_CO_EXISTENCE + "\",s_3).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.NOT_PRECEDENCE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.NOT_PRECEDENCE + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.NOT_PRECEDENCE + "\",s_1,b,s_2).\n"
			+ "automaton(\"" + Template.NOT_PRECEDENCE + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.NOT_PRECEDENCE + "\",s_2,b,s_2).\n"
			+ "automaton(\"" + Template.NOT_PRECEDENCE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.NOT_PRECEDENCE + "\",s_0,b,s_0).\n"
			+ "automaton(\"" + Template.NOT_PRECEDENCE + "\",s_0,a,s_1).\n"
			+ "automaton(\"" + Template.NOT_PRECEDENCE + "\",s_1,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.NOT_PRECEDENCE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.NOT_PRECEDENCE + "\",s_0).\n"
			+ "accepting(\"" + Template.NOT_PRECEDENCE + "\",s_1).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_0,a,s_3).\n"
			+ "automaton(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_3,b,s_1).\n"
			+ "automaton(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_3,c,s_3).\n"
			+ "automaton(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_2,b,s_2).\n"
			+ "automaton(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_1,b,s_1).\n"
			+ "automaton(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_2,a,s_1).\n"
			+ "automaton(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_1,a,s_1).\n"
			+ "automaton(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_3,a,s_3).\n"
			+ "automaton(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_0,b,s_2).\n"
			+ "\n"
			+ "initial(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_0).\n"
			+ "accepting(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_2).\n"
			+ "accepting(\"" + Template.NOT_RESPONDED_EXISTENCE + "\",s_3).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.NOT_RESPONSE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.NOT_RESPONSE + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.NOT_RESPONSE + "\",s_1,b,s_2).\n"
			+ "automaton(\"" + Template.NOT_RESPONSE + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.NOT_RESPONSE + "\",s_2,b,s_2).\n"
			+ "automaton(\"" + Template.NOT_RESPONSE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.NOT_RESPONSE + "\",s_0,b,s_0).\n"
			+ "automaton(\"" + Template.NOT_RESPONSE + "\",s_0,a,s_1).\n"
			+ "automaton(\"" + Template.NOT_RESPONSE + "\",s_1,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.NOT_RESPONSE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.NOT_RESPONSE + "\",s_0).\n"
			+ "accepting(\"" + Template.NOT_RESPONSE + "\",s_1).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.NOT_SUCCESSION + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.NOT_SUCCESSION + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.NOT_SUCCESSION + "\",s_1,b,s_2).\n"
			+ "automaton(\"" + Template.NOT_SUCCESSION + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.NOT_SUCCESSION + "\",s_2,b,s_2).\n"
			+ "automaton(\"" + Template.NOT_SUCCESSION + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.NOT_SUCCESSION + "\",s_0,b,s_0).\n"
			+ "automaton(\"" + Template.NOT_SUCCESSION + "\",s_0,a,s_1).\n"
			+ "automaton(\"" + Template.NOT_SUCCESSION + "\",s_1,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.NOT_SUCCESSION + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.NOT_SUCCESSION + "\",s_0).\n"
			+ "accepting(\"" + Template.NOT_SUCCESSION + "\",s_1).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.PRECEDENCE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.PRECEDENCE + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.PRECEDENCE + "\",s_0,b,s_1).\n"
			+ "automaton(\"" + Template.PRECEDENCE + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.PRECEDENCE + "\",s_2,b,s_2).\n"
			+ "automaton(\"" + Template.PRECEDENCE + "\",s_0,a,s_2).\n"
			+ "automaton(\"" + Template.PRECEDENCE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.PRECEDENCE + "\",s_1,b,s_1).\n"
			+ "automaton(\"" + Template.PRECEDENCE + "\",s_1,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.PRECEDENCE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.PRECEDENCE + "\",s_0).\n"
			+ "accepting(\"" + Template.PRECEDENCE + "\",s_2).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.RESPONDED_EXISTENCE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.RESPONDED_EXISTENCE + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.RESPONDED_EXISTENCE + "\",s_0,b,s_1).\n"
			+ "automaton(\"" + Template.RESPONDED_EXISTENCE + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.RESPONDED_EXISTENCE + "\",s_0,a,s_2).\n"
			+ "automaton(\"" + Template.RESPONDED_EXISTENCE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.RESPONDED_EXISTENCE + "\",s_1,b,s_1).\n"
			+ "automaton(\"" + Template.RESPONDED_EXISTENCE + "\",s_2,b,s_1).\n"
			+ "automaton(\"" + Template.RESPONDED_EXISTENCE + "\",s_1,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.RESPONDED_EXISTENCE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.RESPONDED_EXISTENCE + "\",s_0).\n"
			+ "accepting(\"" + Template.RESPONDED_EXISTENCE + "\",s_1).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.RESPONSE + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.RESPONSE + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.RESPONSE + "\",s_0,b,s_0).\n"
			+ "automaton(\"" + Template.RESPONSE + "\",s_0,a,s_1).\n"
			+ "automaton(\"" + Template.RESPONSE + "\",s_1,b,s_0).\n"
			+ "automaton(\"" + Template.RESPONSE + "\",s_1,a,s_1).\n"
			+ "\n"
			+ "initial(\"" + Template.RESPONSE + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.RESPONSE + "\",s_0).\n"
			+ "\n"
			+ "\n"
			+ "automaton(\"" + Template.SUCCESSION + "\",s_0,a,s_3).\n"
			+ "automaton(\"" + Template.SUCCESSION + "\",s_1,c,s_1).\n"
			+ "automaton(\"" + Template.SUCCESSION + "\",s_2,c,s_2).\n"
			+ "automaton(\"" + Template.SUCCESSION + "\",s_3,b,s_1).\n"
			+ "automaton(\"" + Template.SUCCESSION + "\",s_3,c,s_3).\n"
			+ "automaton(\"" + Template.SUCCESSION + "\",s_2,a,s_2).\n"
			+ "automaton(\"" + Template.SUCCESSION + "\",s_2,b,s_2).\n"
			+ "automaton(\"" + Template.SUCCESSION + "\",s_1,a,s_3).\n"
			+ "automaton(\"" + Template.SUCCESSION + "\",s_0,c,s_0).\n"
			+ "automaton(\"" + Template.SUCCESSION + "\",s_1,b,s_1).\n"
			+ "automaton(\"" + Template.SUCCESSION + "\",s_3,a,s_3).\n"
			+ "automaton(\"" + Template.SUCCESSION + "\",s_0,b,s_2).\n"
			+ "\n"
			+ "initial(\"" + Template.SUCCESSION + "\",s_0).\n"
			+ "\n"
			+ "accepting(\"" + Template.SUCCESSION + "\",s_0).\n"
			+ "accepting(\"" + Template.SUCCESSION + "\",s_1).\n"
			+ "\n"
			+ "\n";
}
